### PR TITLE
Don't log debugging messages as error messages

### PR DESCRIPTION
**Pull request by TylerLubeck**
this was dumb

### CODE REVIEW

**Comment by TylerLubeck** [comment]
@tknickman care to comment?

**Comment by tknickman** [comment]
😬 I take no responsibility for anything in `zookeeper.py`.

(jk - I wrote most of this, happy to help with reviews if you tag me)

**Comment by tknickman** [comment]
Also, :shipit:

**Comment by TylerLubeck** [comment]
Closing in favor of #19 . It's the same thing but not done through the git ui

**Pull request closed without merging**
